### ISSUE TITLE
push access

### ISSUE THREAD

**Issue by sten0** [debian-calibre/html5-parser#3]
Please give me push access to this repo.  For now all I have is a bullseye-backports branch, but I might need to make other changes in the future.

Thanks!

**Comment by norbusan** [comment]
I already sent you an invitation long long time ago, which you let slip ... I resent it. It is for the "debian-calibre" organization.

**Comment by sten0** [comment]
Norbert Preining ***@***.***> writes:

> I already sent you an invitation long long time ago, which you let
> slip ...

Ah, yes to debian-calibre org vs html5-parser, 29 March.  Sorry, that
was a week where I had no free time and poor connectivity.

> I resent it. It is for the "debian-calibre" organization.
>

Thanks!

**Comment by sten0** [comment]
Sadly that didn't do the trick...  Maybe I did accept that invite after all, and maybe repo-level access isn't being inherited by group-level?
```
ERROR: Permission to debian-calibre/html5-parser.git denied to sten0.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by sten0** [comment]
Or maybe "Member" level permissions aren't high enough?

**Comment by norbusan** [comment]
Done now. You are owner in the debian-calibre group, like Yokota-san. That should be enough to have access to all repos.

And since I will probably leave this group anyway, please feel free to coordinate with Yokota-san about future development. Thanks

**Comment by sten0** [comment]
Norbert Preining ***@***.***> writes:

> Done now. You are owner in the debian-calibre group, like Yokota-san. That should be enough to have access to all repos.
>

Thanks!

> And since I will probably leave this group anyway, please feel free to coordinate with Yokota-san about future development. Thanks
>

Sure thing, will do.  By the way, if ever there's a subtle issue that
poses a language barrier, do you know any Japanese speaking DDs who
might be willing to help?  I know Osamu Aoki and Hideki Yamane, but
ideally someone who is already involved in mentoring would be best.  I
just want to make things as pleasant for Yokota-san as possible, you
know?

If you leave this group, will Yokota-san and I receive a notification?
If not, please send one so that we can drop you from Uploaders.

On a tangential note, if you end up on an OS other than Debian, please
let me know, since I'm curious if there are alternatives that compare
favourably to our high standards :-)  I'll try to follow you blog more
regularly too!

Take care,
Nicholas
